### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by qloakongithub**

### CODE REVIEW

**Comment by ILOVETOMAKESTUFF** [comment]
I understand the underline, but what is the tailwind for?

**Comment by ILOVETOMAKESTUFF** [comment]
@Autofirejm, don't merge it just yet.

**Comment by qloakongithub** [comment]
ILTMS https://tailwindcss.com/ check this out for some info on tailwind

**Comment by ILOVETOMAKESTUFF** [comment]
@qloakongithub Okay, but why did you change the JS tag if this has to do with CSS?

**Comment by qloakongithub** [comment]
Because it's required to use custom CSS properties to enhance the webpage

**Comment by ILOVETOMAKESTUFF** [comment]
> Because it's required to use custom CSS properties to enhance the webpage

What does this have to do with JS?

**Comment by qloakongithub** [comment]
> > Because it's required to use custom CSS properties to enhance the webpage
> 
> What does this have to do with JS?

Custom CSS requires JS.

**Comment by ILOVETOMAKESTUFF** [comment]
Alright, I'll merge and see what it does...

**Comment by ILOVETOMAKESTUFF** [comment]
Yikes, I don't really like it. (no offense)

**Comment by qloakongithub** [comment]
Alright. If there are any new issues brought up and they are traced to this pull, feel free to remove them. If you want to use the style options embedded by Tailwind, check out the documentation [here.](https://tailwindcss.com/docs/installation/play-cdn)

**Comment by webdev03** [comment]
As a tailwind user, @qloakongithub why? I think this kind of project wouldn't need it, and not many people know Tailwind.
It might be why nobody contributes to scratchinfo lol

**Pull request merged**
