### PR TITLE
WIP: Improvements

### PR DESCRIPTION
**Pull request by webdev03**
Work in progress!

- [x] Improve title
- [x] Add nav element
- [x] Change the font
- [x] Make the navbar take the full width
- [x] Make the navbar hover link colour better
- [x] Move navbar items to right
- [x] Add "The Forum Participators" text
- [x] Add 2 meta tags
- [x] Stop using scratch assets CDN
- [x] Fix the list to use UL and LI
- [x] Move the joining page to a new page
- [x] Move the Contact Us to a new page
- [x] Make the curators list an UL
- [x] Make the managers list an UL

Things which can be done in another PR
- Use GitHub Actions to update the curators and managers list (I can do this if you need)

The Forum Helper's website doesn't work well without Javascript since the navbar is managed by a JS file. Should I do the same thing or not?

### CODE REVIEW

**Comment by webdev03** [comment]
If you use the file viewer .html to open the site, then you could use replit, or you can tell me and I can change it back.

**Comment by webdev03** [comment]
@Autofirejm @ILOVETOMAKESTUFF can you review?

**Comment by ILOVETOMAKESTUFF** [comment]
> Work in progress!
> 
> * [x]  Improve title
> * [x]  Add nav element
> * [x]  Change the font
> * [x]  Make the navbar take the full width
> * [x]  Make the navbar hover link colour better
> * [x]  Move navbar items to right
> * [x]  Add "The Forum Participators" text
> * [x]  Add 2 meta tags
> * [x]  Stop using scratch assets CDN
> * [x]  Fix the list to use UL and LI
> * [x]  Move the joining page to a new page
> * [x]  Move the Contact Us to a new page
> * [x]  Make the curators list an UL
> * [x]  Make the managers list an UL
> 
> Things which can be done in another PR
> 
> * Use GitHub Actions to update the curators and managers list (I can do this if you need)
> 
> The Forum Helper's website doesn't work well without Javascript since the navbar is managed by a JS file. Should I do the same thing or not?

Sure!



> If you use the file viewer .html to open the site, then you could use replit, or you can tell me and I can change it back.

Replit is blocked for me

> @Autofirejm @ILOVETOMAKESTUFF can you review?

Sure!

**Comment by webdev03** [comment]
Oh no.. Can you see if you can still find a way to develop with this? Or should I switch to the old system?

**Review by ILOVETOMAKESTUFF — APPROVED** [review]
I think I know what most of the code does, but I can't understand some of it. I'll merge it, (or should I? Idk what will happen, I need advice, though I trust you) I hope it goes well!

**Comment by webdev03** [comment]
Tell me what you don't understand... because I kept on typing random things to get it to work LOL 🤣

**Comment by ILOVETOMAKESTUFF** [comment]
> Tell me what you don't understand... because I kept on typing random things to get it to work LOL 🤣

What does the addmembers.yml do? (I know I suck at the programming languages, so I can't read it too well...) I do understand the update.js, (yeah, I know the basics) I kinda seem to know what the JSON file does, contact.html is pretty straightforward, (like all of the .html files). You did right to delete the .js file (it didn't work for some reason) and the CSS change was great (I mean, now you could add lists!)

**Comment by webdev03** [comment]
`addmembers.yml` is the github action - you can learn more about Actions at https://docs.github.com/en/actions but it basically updates the data.json like the update.js file. For the CSS thing I used VSCode, since when you hover over the `nav ul` part of CSS then it shows a little diagram like this:
```html
<nav>
  …
    <li>
      …
        <a>
```

**Comment by webdev03** [comment]
I'm going to merge it now!

**Comment by ILOVETOMAKESTUFF** [comment]
I'm going to have to make a body padding since it is blocked by the navbar

**Pull request merged**
