### PR TITLE
Add Parody of "Google Analytics Warning"

### PR DESCRIPTION
**Pull request by Mbrick2**
Parody of image
(its says ... DOESNT ...)
Just more TFH Parody

### CODE REVIEW

**Comment by Autofirejm** [comment]
good idea 
helps with the parody aspect

**Comment by webdev03** [comment]
That's stealing code isn't it?

**Comment by ILOVETOMAKESTUFF** [comment]
What is google analytics?

**Comment by webdev03** [comment]
Please don't use Google Analytics. It requires you to add a privacy policy to your site or risk legal problems. Also, it gives data to Google. I still don't understand why TFH has Google Analytics.

**Pull request merged**
